"""Updated a bit132

Revision ID: 1c1bf553c91b
Revises: 3866a6de4ccd
Create Date: 2024-05-03 23:01:40.007992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1bf553c91b'
down_revision = '3866a6de4ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('order_status_id_fkey', type_='foreignkey')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('order_status_id_fkey', 'order', ['status_id'], ['id'])

    # ### end Alembic commands ###
