"""Samples updated

Revision ID: 1e482e7bcd0f
Revises: 3d8f96f919fd
Create Date: 2024-05-03 13:26:19.674999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e482e7bcd0f'
down_revision = '3d8f96f919fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_model_pkey'),
    sa.UniqueConstraint('name', name='category_model_name_key')
    )
    # ### end Alembic commands ###
