"""OrderItems

Revision ID: 1fa8123a20db
Revises: 9c2a3e2af4a8
Create Date: 2024-05-03 14:13:38.690341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa8123a20db'
down_revision = '9c2a3e2af4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplie', schema=None) as batch_op:
        batch_op.drop_constraint('supplie_sample_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'supplie', ['sample_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('supplie_sample_id_fkey', 'sample', ['sample_id'], ['id'])

    # ### end Alembic commands ###
