"""Updated a bit12

Revision ID: 3866a6de4ccd
Revises: 763c04c90d31
Create Date: 2024-05-03 22:54:27.323725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3866a6de4ccd'
down_revision = '763c04c90d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supply')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('order_status_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['status_id'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_status_fkey', 'order', ['status'], ['id'])
        batch_op.drop_column('status_id')

    op.create_table('supply',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('state_on_supp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=90), autoincrement=False, nullable=True),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], name='supply_sample_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='supply_pkey')
    )
    # ### end Alembic commands ###
