"""Updated a bit1321

Revision ID: 539eb219688e
Revises: 1c1bf553c91b
Create Date: 2024-05-03 23:03:53.303974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539eb219688e'
down_revision = '1c1bf553c91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_status')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_id')

    op.create_table('order_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='order_status_pkey')
    )
    # ### end Alembic commands ###
