"""Updated a bit

Revision ID: 763c04c90d31
Revises: 2f4916cdf857
Create Date: 2024-05-03 22:43:24.523284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763c04c90d31'
down_revision = '2f4916cdf857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplie', schema=None) as batch_op:
        batch_op.drop_constraint('supplie_sample_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sample', ['sample_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('supplie_sample_id_fkey', 'supplie', ['sample_id'], ['id'])

    # ### end Alembic commands ###
