"""Orders

Revision ID: 9c2a3e2af4a8
Revises: 52d6553a916e
Create Date: 2024-05-03 14:04:03.158204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2a3e2af4a8'
down_revision = '52d6553a916e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('sample_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('sample_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
